### ISSUE TITLE
API KEY problem in code

### ISSUE THREAD

**Issue by idkfa17** [jbram22/ev_sports_betting#1]
Hi, i got some issued regarding "PD" files. "Pd is not refined" i get as an error i VScode when i enter your code. Any idea how to solve this issue? I attach an image with all the issues. 

![code](https://github.com/jbram22/ev_sports_betting/assets/157232377/f5f3ce27-d1cf-4500-b1fd-6dcfb35fb97c)

Thanks in advance!

**Comment by jbram22** [comment]
Hello! Thank you for taking a look at the package! In short, I think your error is simple to fix. At the top of the files you are trying to run, just insert the following code:

import requests
import pandas as pd

Let me know if that helps. Regardless, I will update the code tomorrow to reflect these changes, so you do not encounter these errors.

**Comment by idkfa17** [comment]
Thanks for getting back to me, i Will try that out later today. I now see that my headline was wrong, i had some issues about the key when i started writing but i seemed to fixed that haha. Sorry for the confusion 😀. Skickat från min iPhone20 jan. 2024 kl. 23:11 skrev Jason Bram ***@***.***>:﻿
Hello! Thank you for taking a look at the package! In short, I think your error is simple to fix. At the top of the files you are trying to run, just insert the following code:
import requests
import pandas as pd
Let me know if that helps. Regardless, I will update the code tomorrow to reflect these changes, so you do not encounter these errors.

**Comment by idkfa17** [comment]
hi again,

yeah i dont seem to get this to work. i do however have about 0% skill in
this. I made the code work but i cant seem to get it to run, i tried using
robocorp, is this completley retarded or is this the way you should get it
running?

Den lör 20 jan. 2024 kl 23:11 skrev Jason Bram ***@***.***>:

**Comment by jbram22** [comment]
Hi! Im very sorry to hear that, but I am in the process of giving this repo a total re-vamp, and will release not only an updated repo, but an updated README to include installation and usage examples. 

Help is on the way !

**Comment by idkfa17** [comment]
that would be awesome man! i am slowly getting there tho, i have managed to
get the bot started now, and are currently trying to get the results to a
CSV file or excel :). learing is fun! even if it brings some gray hairs.

Den sön 21 jan. 2024 kl 21:10 skrev Jason Bram ***@***.***>:

**Comment by jbram22** [comment]
Glad to hear your getting things to work! I just re-vamped the repo, so check it out and let me know if you have any questions. I have a long list of things Im going to add to the repo, so stay tuned for new functionality
